### ISSUE TITLE
attaching to tangle is taking too long in the update 2.5.1

### ISSUE THREAD

**Issue by fox8411** [iotaledger/wallet#331]
after upgrading to 2.5.1 I tried to attach to the tangle, but it is taking too long, about 12 hours and counting trying to attach, how long should i wait?
I have an additional problem, before the update I had an unconfirmed transaction from my wallet to bitfinex and now it seems that I have a double spend problem because in "show bundle" the button reattach does not appear
MIN WEIGHT is 14 and I've tried with several nodes

**Comment by fox8411** [comment]
the problem was solved, the update to 2.5.1 was not working for me, I came back to 2.5.0 and got my iota´s back =)

**Comment by ThisIsIota** [comment]
yeah, the 2.5.1 update really doesnt solve the problems. having similar problems with invalid hashs
